### ISSUE TITLE
rstats fps throws error.

### ISSUE THREAD

**Issue by karingneha** [spite/rstats#9]
I just with rstats and using the very basic code :  rS( 'frame' ).start();
    rS( 'rAF' ).tick();
    rS( 'FPS' ).frame();--> this  line throws error "Cannot read property 'interpolate' of undefined" . any way i can fix it?

**Comment by spite** [comment]
Do you have any code online I can check to see what's going on?

**Comment by luigimannoni** [comment]
Hello,
I am getting the same error, you can find the code used on this codepen: http://codepen.io/luigimannoni/pen/RWYyJo

**Comment by spite** [comment]
My apologies to both: i forgot to add a check for defines. https://github.com/spite/rstats/commit/23d114588a140a9356d9c0f88c15356bc10a4292 should fix it

**Comment by luigimannoni** [comment]
That was an easy one, should've figured it by myself :)

Thanks
